name: Python package

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3.8
        uses: actions/setup-python@v2
        with:
          python-version: 3.8
      - name: Install poetry
        run: |
          python -m pip install --upgrade pip
          pip install poetry
      - name: Install project
        run: poetry install
      - name: Code style
        run: |
          poetry run isort --check-only
          poetry run black --check
      - name: Lint code
        run: poetry run sh ./utils/check_code.sh
      - name: Unit tests
        run: poetry run pytest